### ISSUE TITLE
Segmentation fault on execution

### ISSUE THREAD

**Issue by WCBROW01** [bjoelkrug78/datacassette#6]
After compiling datacassettereader.c, I get a segmentation fault when opening it, and datacassettewriter.c doesn't compile at all. Am I missing dependencies?

The compilation output for datacassettewriter.c is
```
/tmp/ccRHSQL5.o: In function `main':
datacassettewriter.c:(.text+0x443): undefined reference to `sin'
datacassettewriter.c:(.text+0x4b5): undefined reference to `sin'
collect2: error: ld returned 1 exit status
```

**Comment by bjoelkrug78** [comment]
For compiling the writer please use gcc -lm

**Comment by bjoelkrug78** [comment]
The segfault in reader could happen because output.wav is not found

**Comment by WCBROW01** [comment]
Same error with gcc -lm

**Comment by bjoelkrug78** [comment]
gcc -lm datacassettewriter.c still gives you the undefined references to "sin"?

**Comment by bjoelkrug78** [comment]
I just tried it and get the following without -lm and with it:

/data/boelkrug/temp/datacassette$ gcc datacassettewriter.c
/build/arc/temp/243809283/ccAJyzh9.o: In function `main':
datacassettewriter.c:(.text+0x39c): undefined reference to `sin'
datacassettewriter.c:(.text+0x3fd): undefined reference to `sin'
collect2: error: ld returned 1 exit status

/data/boelkrug/temp/datacassette$ gcc -lm datacassettewriter.c
/data/boelkrug/temp/datacassette$

**Comment by WCBROW01** [comment]
will@will-MacPro:~/datacassette$ gcc -lm datacassettewriter.c
/tmp/ccEdU1tZ.o: In function `main':
datacassettewriter.c:(.text+0x443): undefined reference to `sin'
datacassettewriter.c:(.text+0x4b5): undefined reference to `sin'
collect2: error: ld returned 1 exit status

**Comment by bjoelkrug78** [comment]
It seems you are on a Mac. Haven’t tried to compile it there but can you try to use the -lm last?
gcc datacassettewriter.c -lm

**Comment by WCBROW01** [comment]
I'm actually on Linux, I'm just running it on an old Mac Pro. macOS is nowhere to be found. The OS is KDE Neon, which is Ubuntu 16.04 with a rolling KDE stack.

Edit: and that worked. Now I'm confused.

**Comment by bjoelkrug78** [comment]
Does putting gcc datacassettewriter.c -lm work for you?

**Comment by WCBROW01** [comment]
Yes, but datacassettereader still segfaults.

Edit: I'm an idiot, didn't name it output.wav. Is there a way to write actual files?

**Comment by bjoelkrug78** [comment]
Did you provide it with an output.wav that it can decode?
For easiest testing you can simple run datacassettewriter, let it generate
input.wav (which you are supposed to use to play and record on your
tapedeck), copy that input.wav to output.wav and
run "datacassettereader". That should in return decode output.wav and
create an output.txt.
You can then compare input.txt to output.txt.
It should be the same if you simply do the simple test of input.wav ->
output.wav

**Comment by WCBROW01** [comment]
Yeah, I tried that and it works. I want to figure out how to use an actual file, however. How would I go about that?

**Comment by bjoelkrug78** [comment]
Have a look at the USAGE description:

datacassettewriter.c: This will generate a random sequence of bits. A total
of 8192 frames of 1024 bits data each will be generated along with an 8 bit
header and 8 bit trailer. The sequence will be stored to input.txt

Alongside of it a WAV file will be created (with 96kHz sample rate, stereo,
16 bit resolution) which should be used to play from your laptop (using
Audacity on Windows for example) and be recorded by your tapedeck. Make
sure you have set the record level correctly on the tape deck. Once you
have the WAV file recorded, then use your tape deck to play back the
recorded sounds and sample them with 96kHz sample rate, stereo, 16 bit
resolution (using Audacity for example).

datacassettereader.c: This will take in a WAV file recorded previously and
will decode it and create output.txt.


So simply use datacassettewriter to create the WAV file, use Audacity to
play it, record on your tape deck. Then play it back from your tape deck,
record in Audacity with 96kHz sample rate, stereo, 16 bit resolution and
feed that .wav file to datacassettereader.

**Comment by bjoelkrug78** [comment]
Oh, if you want to use an actual file to encode, datacassettewriter has to
be adapted to read in the file instead of creating random bits.
Haven't done that yet.
As I wanted to get a feeling on bit error rate.

On Tue, Apr 24, 2018 at 3:40 PM, Barefoot Family <bernhard.oelkrug@gmail.com

**Comment by WCBROW01** [comment]
Ah, that makes sense. Would also be a good idea to add error correction and such too. I'm looking forward to seeing how this turns out. I don't have a cassette deck yet, but I do have a VHS Hi-Fi VCR, which can record a much longer length of audio than a standard cassette, so how it turns out with that would also be interesting.

**Comment by bjoelkrug78** [comment]
Yes, I want to all add this step by step. Really looking forward to some
help here too.
It definitely already has higher data rate than what would have been used
in 8-bit times.
You should be able to use the VHS VCR with the same program if you have the
cables connected.

**Comment by WCBROW01** [comment]
I'd help if I could, but I don't really know C. I'm testing putting input.txt into a Kansas City Standard encoder which is 1200 baud, and it's going up to 5 hours and it's not nearly done. This is definitely much faster right now. Another thing to note is that currently I have no devices that support 96KHz output, so I'm not sure if it will work

**Comment by bjoelkrug78** [comment]
I don't think you really understood me.
Why would you use the already encoded .wav file and send it through the
Kansas City Standard encoder?
The file you actually want to encode/save to tape is input.txt (minus the
added information on frame/header etc...).
What would you have gained using my program?
Please let me know what you are actually trying to achieve.

**Comment by WCBROW01** [comment]
I put in the input.txt, not input.wav. I was trying to compare how long it would take to read input.txt with KCS and your program.

Edit: Oh, I see I made a typo.

Edit 2: I have just verified that after upsampling from a 48KHz sampling rate to 96KHz, the file is read properly.

**Comment by bjoelkrug78** [comment]
Ah ok, understood. My program uses 9600 baud so should be 8x faster.
I will add the file feature next and then go for the error correction.

**Comment by WCBROW01** [comment]
I will close this report. Thanks for your help.
